// AUTO-GENERATED by scripts/organize-imported-media.py
// Source: https://www.ontarioskateboarding.ca (scraped assets)
// Do not edit by hand — re-run the script to refresh.

export type PageMedia = {
  readonly url: string;
  readonly path: string;
  readonly title: string;
  readonly slug: string;
  readonly images: readonly string[];
  readonly videos: readonly string[];
};

export const home: PageMedia = {
  url: "https://www.ontarioskateboarding.ca",
  path: "/",
  title: "HOME",
  slug: "home",
  images: [
    "/imported/home/01.png",
    "/imported/home/02.jpg",
    "/imported/home/03.jpg",
    "/imported/home/04.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--zero-deck/02.jpg",
    "/imported/the-board/01.png",
    "/imported/the-board/02.png",
    "/imported/the-board/03.png",
  ],
  videos: [
  ],
} as const;

export const about3: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/about-3",
  path: "/about-3",
  title: "About",
  slug: "about-3",
  images: [
    "/imported/about-3/01.jpg",
    "/imported/about-3/02.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--zero-deck/02.jpg",
    "/imported/the-board/09.jpg",
    "/imported/the-board/12.jpg",
  ],
  videos: [
  ],
} as const;

export const aboutus: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/about-us",
  path: "/about-us",
  title: "ABOUT US",
  slug: "about-us",
  images: [
    "/imported/about-us/01.png",
    "/imported/about-us/02.png",
    "/imported/about-us/03.png",
    "/imported/about-us/04.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const ams: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/ams",
  path: "/ams",
  title: "AMS",
  slug: "ams",
  images: [
    "/imported/ams/01.jpg",
    "/imported/ams/02.jpg",
    "/imported/ams/03.jpg",
    "/imported/ams/04.png",
    "/imported/ams/05.jpeg",
    "/imported/ams/06.jpg",
    "/imported/ams/07.jpg",
    "/imported/ams/08.jpg",
    "/imported/ams/09.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const archives: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/archives",
  path: "/archives",
  title: "ARCHIVE",
  slug: "archives",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blog: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/blog",
  path: "/blog",
  title: "BLOG AND MORE",
  slug: "blog",
  images: [
    "/imported/blog/01.png",
    "/imported/blog/02.png",
    "/imported/home/01.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--after_school_specialists_skateboarding101-2nd-annual-results/01.png",
    "/imported/post--after_school_specialists_skateboarding101/01.jpg",
    "/imported/post--change-is-coming/01.png",
    "/imported/post--comacan-interviews-os/01.jpeg",
    "/imported/post--go-skateboarding/01.png",
    "/imported/post--inaugural-os-board-meeting-february-22-2023/01.jpg",
    "/imported/post--kickflip_kickoff-second-annual-outdoor-season-kickoff-challenge/01.jpg",
    "/imported/post--kickflip_kickoff/01.jpg",
    "/imported/post--ontario-brand-feature-troubl3-skateboards/01.jpg",
    "/imported/post--ontario-brand-feature-troubl3-skateboards/02.jpg",
    "/imported/post--ontario-skateboarding-releases-new-t-shirt-design/01.png",
    "/imported/post--skatergirlshowcase2022-is-what-august-is-all-about/01.jpg",
    "/imported/post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast/01.png",
    "/imported/post--sponsorme_troubl3/01.jpg",
    "/imported/post--winners-announced/01.jpg",
    "/imported/the-board/01.png",
  ],
  videos: [
  ],
} as const;

export const canadaskateboardsslurpeeopen2023: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/canada-skateboards-slurpee-open-2023",
  path: "/canada-skateboards-slurpee-open-2023",
  title: "Canada Skateboards Slurpee Open 2023",
  slug: "canada-skateboards-slurpee-open-2023",
  images: [
    "/imported/canada-skateboards-slurpee-open-2023/01.jpg",
    "/imported/canada-skateboards-slurpee-open-2023/02.jpg",
    "/imported/canada-skateboards-slurpee-open-2023/03.jpg",
    "/imported/canada-skateboards-slurpee-open-2023/04.jpg",
    "/imported/canada-skateboards-slurpee-open-2023/05.jpg",
    "/imported/canada-skateboards-slurpee-open-2023/06.jpg",
    "/imported/canada-skateboards-slurpee-open-2023/07.jpg",
    "/imported/canada-skateboards-slurpee-open-2023/08.jpg",
    "/imported/dunbat-2018/01.png",
    "/imported/dunbat-2018/09.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const shopCategoryallproducts: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/category/all-products",
  path: "/category/all-products",
  title: "All Products",
  slug: "category--all-products",
  images: [
    "/imported/category--all-products/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--copy-of-i-m-a-product/01.webp",
    "/imported/product-page--shorty-s-t-shirt/01.jpg",
    "/imported/product-page--skate-toque/01.webp",
    "/imported/product-page--zero-deck/01.webp",
    "/imported/product-page--zero-deck/02.jpg",
  ],
  videos: [
  ],
} as const;

export const comingsoon03: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/coming-soon-03",
  path: "/coming-soon-03",
  title: "SHOP",
  slug: "coming-soon-03",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const contact2: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/contact-2",
  path: "/contact-2",
  title: "Contact",
  slug: "contact-2",
  images: [
    "/imported/contact-2/01.jpg",
    "/imported/dunbat-2018/09.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const contactus: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/contact-us",
  path: "/contact-us",
  title: "SHOP",
  slug: "contact-us",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--copy-of-i-m-a-product/01.webp",
    "/imported/product-page--shorty-s-t-shirt/01.jpg",
    "/imported/product-page--skate-toque/01.webp",
    "/imported/product-page--zero-deck/01.webp",
  ],
  videos: [
  ],
} as const;

export const dunbat2018: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/dunbat-2018",
  path: "/dunbat-2018",
  title: "DunBat 2018",
  slug: "dunbat-2018",
  images: [
    "/imported/dunbat-2018/01.png",
    "/imported/dunbat-2018/02.jpg",
    "/imported/dunbat-2018/03.jpg",
    "/imported/dunbat-2018/04.jpg",
    "/imported/dunbat-2018/05.jpg",
    "/imported/dunbat-2018/06.jpg",
    "/imported/dunbat-2018/07.jpg",
    "/imported/dunbat-2018/08.jpg",
    "/imported/dunbat-2018/09.jpg",
    "/imported/dunbat-2018/10.jpg",
    "/imported/dunbat-2018/11.jpg",
    "/imported/dunbat-2018/12.jpg",
    "/imported/dunbat-2018/13.jpg",
    "/imported/dunbat-2018/14.jpg",
    "/imported/dunbat-2018/15.jpg",
    "/imported/dunbat-2018/16.jpg",
    "/imported/dunbat-2018/17.jpg",
    "/imported/dunbat-2018/18.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const dunbat2021: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/dunbat-2021",
  path: "/dunbat-2021",
  title: "DunBat 2021",
  slug: "dunbat-2021",
  images: [
    "/imported/dunbat-2018/01.png",
    "/imported/dunbat-2018/09.jpg",
    "/imported/dunbat-2021/01.jpg",
    "/imported/dunbat-2021/02.jpg",
    "/imported/dunbat-2021/03.jpg",
    "/imported/dunbat-2021/04.jpg",
    "/imported/dunbat-2021/05.jpg",
    "/imported/dunbat-2021/06.jpg",
    "/imported/dunbat-2021/07.jpg",
    "/imported/dunbat-2021/08.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const dunbat2022: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/dunbat-2022",
  path: "/dunbat-2022",
  title: "DunBat 2022",
  slug: "dunbat-2022",
  images: [
    "/imported/dunbat-2018/01.png",
    "/imported/dunbat-2018/09.jpg",
    "/imported/dunbat-2022/01.jpg",
    "/imported/dunbat-2022/02.jpg",
    "/imported/dunbat-2022/03.png",
    "/imported/dunbat-2022/04.png",
    "/imported/dunbat-2022/05.jpg",
    "/imported/dunbat-2022/06.png",
    "/imported/dunbat-2022/07.jpg",
    "/imported/dunbat-2022/08.png",
    "/imported/dunbat-2022/09.png",
    "/imported/dunbat-2022/10.jpg",
    "/imported/dunbat-2022/11.jpg",
    "/imported/dunbat-2022/12.png",
    "/imported/dunbat-2022/13.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailscampbellfordjam: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/campbellford-jam",
  path: "/event-details/campbellford-jam",
  title: "Campbellford Jam",
  slug: "event-details--campbellford-jam",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--66-thieves-partner-with-os/01.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailscharityskateathon: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/charity-skate-a-thon",
  path: "/event-details/charity-skate-a-thon",
  title: "Charity Skate-A-Thon",
  slug: "event-details--charity-skate-a-thon",
  images: [
    "/imported/event-details--charity-skate-a-thon/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailscharityskateathon1: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/charity-skate-a-thon-1",
  path: "/event-details/charity-skate-a-thon-1",
  title: "Charity Skate-A-Thon",
  slug: "event-details--charity-skate-a-thon-1",
  images: [
    "/imported/event-details--charity-skate-a-thon/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailsdunbat20181: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/dunbat-2018-1",
  path: "/event-details/dunbat-2018-1",
  title: "Dunbat 2018",
  slug: "event-details--dunbat-2018-1",
  images: [
    "/imported/event-details--dunbat-2018-1/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailsgoskateday20241: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/go-skate-day-2024-1",
  path: "/event-details/go-skate-day-2024-1",
  title: "Go Skate Day 2024",
  slug: "event-details--go-skate-day-2024-1",
  images: [
    "/imported/event-details--go-skate-day-2025/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailsgoskateday2025: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/go-skate-day-2025",
  path: "/event-details/go-skate-day-2025",
  title: "Go Skate Day 2025",
  slug: "event-details--go-skate-day-2025",
  images: [
    "/imported/event-details--go-skate-day-2025/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailsshredseriesontarioskateloft: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/shred-series-ontario-skateloft",
  path: "/event-details/shred-series-ontario-skateloft",
  title: "Shred Series - Ontario @ skateloft",
  slug: "event-details--shred-series-ontario-skateloft",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailsskatecreateworkshop: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/skate-create-workshop",
  path: "/event-details/skate-create-workshop",
  title: "Skate & Create Workshop",
  slug: "event-details--skate-create-workshop",
  images: [
    "/imported/event-details--skate-create-workshop/01.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventsEventdetailsskatecreateworkshop1: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-details/skate-create-workshop-1",
  path: "/event-details/skate-create-workshop-1",
  title: "Skate & Create Workshop",
  slug: "event-details--skate-create-workshop-1",
  images: [
    "/imported/event-details--skate-create-workshop/01.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const eventlist: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/event-list",
  path: "/event-list",
  title: "Events",
  slug: "event-list",
  images: [
    "/imported/dunbat-2018/09.jpg",
    "/imported/event-details--charity-skate-a-thon/01.jpg",
    "/imported/event-details--dunbat-2018-1/01.jpg",
    "/imported/event-details--go-skate-day-2025/01.jpg",
    "/imported/event-details--skate-create-workshop/01.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const events: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/events",
  path: "/events",
  title: "EVENTS",
  slug: "events",
  images: [
    "/imported/dunbat-2018/09.jpg",
    "/imported/event-details--charity-skate-a-thon/01.jpg",
    "/imported/event-details--dunbat-2018-1/01.jpg",
    "/imported/event-details--go-skate-day-2025/01.jpg",
    "/imported/event-details--skate-create-workshop/01.png",
    "/imported/events/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const lilrippers: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/lil-rippers",
  path: "/lil-rippers",
  title: "lil Rippers",
  slug: "lil-rippers",
  images: [
    "/imported/lil-rippers/01.jpg",
    "/imported/lil-rippers/02.jpg",
    "/imported/lil-rippers/03.jpg",
    "/imported/lil-rippers/04.jpeg",
    "/imported/lil-rippers/05.png",
    "/imported/lil-rippers/06.png",
    "/imported/lil-rippers/07.jpg",
    "/imported/lil-rippers/08.png",
    "/imported/lil-rippers/09.jpg",
    "/imported/lil-rippers/10.jpg",
    "/imported/lil-rippers/11.jpg",
    "/imported/lil-rippers/12.jpg",
    "/imported/lil-rippers/13.jpg",
    "/imported/lil-rippers/14.png",
    "/imported/lil-rippers/15.gif",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--canadian-skateboard-chronicles-and-os-unite/01.jpg",
  ],
  videos: [
  ],
} as const;

export const links: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/links",
  path: "/links",
  title: "LINKS",
  slug: "links",
  images: [
    "/imported/links/01.jpg",
    "/imported/links/02.png",
    "/imported/links/03.jpg",
    "/imported/links/04.jpg",
    "/imported/links/05.png",
    "/imported/links/06.png",
    "/imported/links/07.jpg",
    "/imported/links/08.png",
    "/imported/links/09.jpg",
    "/imported/links/10.jpg",
    "/imported/links/11.png",
    "/imported/links/12.png",
    "/imported/links/13.png",
    "/imported/links/14.png",
    "/imported/links/15.jpg",
    "/imported/links/16.png",
    "/imported/links/17.png",
    "/imported/links/18.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const news: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/news",
  path: "/news",
  title: "Archrieve",
  slug: "news",
  images: [
    "/imported/event-details--charity-skate-a-thon/01.jpg",
    "/imported/event-details--go-skate-day-2025/01.jpg",
    "/imported/event-details--skate-create-workshop/01.png",
    "/imported/news/01.jpg",
    "/imported/news/02.png",
    "/imported/news/03.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--change-is-coming/01.png",
    "/imported/product-page--copy-of-i-m-a-product/01.webp",
    "/imported/product-page--shorty-s-t-shirt/01.jpg",
    "/imported/product-page--skate-toque/01.webp",
    "/imported/product-page--zero-deck/01.webp",
    "/imported/product-page--zero-deck/02.jpg",
  ],
  videos: [
  ],
} as const;

export const news1: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/news-1",
  path: "/news-1",
  title: "NEWS",
  slug: "news-1",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const og: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/og",
  path: "/og",
  title: "OG",
  slug: "og",
  images: [
    "/imported/og/01.png",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const oglegends1: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/og-legends-1",
  path: "/og-legends-1",
  title: "OG-Legends",
  slug: "og-legends-1",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const originofskateboarding: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/origin-of-skateboarding",
  path: "/origin-of-skateboarding",
  title: "ORIGIN OF SKATEBOARDING",
  slug: "origin-of-skateboarding",
  images: [
    "/imported/origin-of-skateboarding/01.jpg",
    "/imported/origin-of-skateboarding/02.jpg",
    "/imported/origin-of-skateboarding/03.jpg",
    "/imported/origin-of-skateboarding/04.jpg",
    "/imported/origin-of-skateboarding/05.jpg",
    "/imported/origin-of-skateboarding/06.jpg",
    "/imported/origin-of-skateboarding/07.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPost4202021: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/4-20-2021",
  path: "/post/4-20-2021",
  title: "4:20 - 2021",
  slug: "post--4-20-2021",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPost5yearsrunningfy25: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/5-years-running-fy25",
  path: "/post/5-years-running-fy25",
  title: "5 years running! (FY25)",
  slug: "post--5-years-running-fy25",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--change-is-coming/01.png",
  ],
  videos: [
  ],
} as const;

export const blogPost66thievespartnerwithos: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/66-thieves-partner-with-os",
  path: "/post/66-thieves-partner-with-os",
  title: "66 Thieves partner with OS.",
  slug: "post--66-thieves-partner-with-os",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--66-thieves-partner-with-os/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPost66thievestricksandtipsfeaturebacksideflip: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/66-thieves-tricks-and-tips-feature-backside-flip",
  path: "/post/66-thieves-tricks-and-tips-feature-backside-flip",
  title: "66 Thieves - Tricks and Tips Feature (Backside Flip)",
  slug: "post--66-thieves-tricks-and-tips-feature-backside-flip",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostafterschoolspecialistsskateboarding101: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/after_school_specialists_skateboarding101",
  path: "/post/after_school_specialists_skateboarding101",
  title: "#after_school_specialists_skateboarding101",
  slug: "post--after_school_specialists_skateboarding101",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--after_school_specialists_skateboarding101/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostafterschoolspecialistsskateboarding1012ndannualresults: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/after_school_specialists_skateboarding101-2nd-annual-results",
  path: "/post/after_school_specialists_skateboarding101-2nd-annual-results",
  title: "#after_school_specialists_skateboarding101 (2nd Annual Results)",
  slug: "post--after_school_specialists_skateboarding101-2nd-annual-results",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--after_school_specialists_skateboarding101-2nd-annual-results/01.png",
  ],
  videos: [
  ],
} as const;

export const blogPostbehindthesceneaudioseries: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/behind-the-scene-audio-series",
  path: "/post/behind-the-scene-audio-series",
  title: "Behind the Scene - Audio Series",
  slug: "post--behind-the-scene-audio-series",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostblastoff: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/blast-off",
  path: "/post/blast-off",
  title: "BLAST OFF!",
  slug: "post--blast-off",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostcanadianskateboardchroniclesandosunite: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/canadian-skateboard-chronicles-and-os-unite",
  path: "/post/canadian-skateboard-chronicles-and-os-unite",
  title: "Canadian Skateboard Chronicles and OS. unite!",
  slug: "post--canadian-skateboard-chronicles-and-os-unite",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--canadian-skateboard-chronicles-and-os-unite/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostchangeiscoming: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/change-is-coming",
  path: "/post/change-is-coming",
  title: "Change is Coming.",
  slug: "post--change-is-coming",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--change-is-coming/01.png",
    "/imported/post--change-is-coming/02.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostcomacaninterviewsos: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/comacan-interviews-os",
  path: "/post/comacan-interviews-os",
  title: "COMACAN interviews OS.",
  slug: "post--comacan-interviews-os",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--comacan-interviews-os/01.jpeg",
  ],
  videos: [
  ],
} as const;

export const blogPostfinalpostof2023: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/final-post-of-2023",
  path: "/post/final-post-of-2023",
  title: "Final post of 2023",
  slug: "post--final-post-of-2023",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--change-is-coming/01.png",
    "/imported/post--final-post-of-2023/01.png",
    "/imported/post--final-post-of-2023/02.png",
    "/imported/post--final-post-of-2023/03.png",
  ],
  videos: [
  ],
} as const;

export const blogPostgoskateboarding: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/go-skateboarding",
  path: "/post/go-skateboarding",
  title: "Go Skateboarding.",
  slug: "post--go-skateboarding",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--go-skateboarding/01.png",
  ],
  videos: [
  ],
} as const;

export const blogPostgoskateboardingday: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/go-skateboarding-day",
  path: "/post/go-skateboarding-day",
  title: "Go Skateboarding Day!",
  slug: "post--go-skateboarding-day",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--go-skateboarding/01.png",
  ],
  videos: [
  ],
} as const;

export const blogPostinauguralosboardmeetingfebruary222023: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/inaugural-os-board-meeting-february-22-2023",
  path: "/post/inaugural-os-board-meeting-february-22-2023",
  title: "Inaugural OS. Board Meeting - February 22, 2023",
  slug: "post--inaugural-os-board-meeting-february-22-2023",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--inaugural-os-board-meeting-february-22-2023/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostkickflipkickoff: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/kickflip_kickoff",
  path: "/post/kickflip_kickoff",
  title: "#kickflip_kickoff",
  slug: "post--kickflip_kickoff",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--kickflip_kickoff/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostkickflipkickoffsecondannualoutdoorseasonkickoffchallenge: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/kickflip_kickoff-second-annual-outdoor-season-kickoff-challenge",
  path: "/post/kickflip_kickoff-second-annual-outdoor-season-kickoff-challenge",
  title: "#kickflip_kickoff - Second Annual Outdoor Season kickoff challenge",
  slug: "post--kickflip_kickoff-second-annual-outdoor-season-kickoff-challenge",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--kickflip_kickoff-second-annual-outdoor-season-kickoff-challenge/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostmonthlyfeaturesskatersandkeystoneskateshops: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/monthly-features-skaters-and-keystone-skate-shops",
  path: "/post/monthly-features-skaters-and-keystone-skate-shops",
  title: "Monthly Features (Skaters and Keystone Skate Shops)",
  slug: "post--monthly-features-skaters-and-keystone-skate-shops",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostodetothevanoffthewall: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/ode-to-the-van-off-the-wall",
  path: "/post/ode-to-the-van-off-the-wall",
  title: "Ode to the Van - Off the Wall",
  slug: "post--ode-to-the-van-off-the-wall",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--ode-to-the-van-off-the-wall/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostontariobrandfeaturetroubl3skateboards: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/ontario-brand-feature-troubl3-skateboards",
  path: "/post/ontario-brand-feature-troubl3-skateboards",
  title: "Ontario Brand Feature - Troubl3 Skateboards",
  slug: "post--ontario-brand-feature-troubl3-skateboards",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--ontario-brand-feature-troubl3-skateboards/01.jpg",
    "/imported/post--ontario-brand-feature-troubl3-skateboards/02.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostontarioskateboardingreleasesnewtshirtdesign: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/ontario-skateboarding-releases-new-t-shirt-design",
  path: "/post/ontario-skateboarding-releases-new-t-shirt-design",
  title: "Ontario Skateboarding Releases New T-shirt Design",
  slug: "post--ontario-skateboarding-releases-new-t-shirt-design",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--ontario-skateboarding-releases-new-t-shirt-design/01.png",
  ],
  videos: [
  ],
} as const;

export const blogPostoscelebratesearthdaysoshouldyou: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/os-celebrates-earth-day-so-should-you",
  path: "/post/os-celebrates-earth-day-so-should-you",
  title: "OS. Celebrates Earth Day! (so should you)",
  slug: "post--os-celebrates-earth-day-so-should-you",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--os-celebrates-earth-day-so-should-you/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostossignspetitiontoopenontarioskateparksduringthethirdwaveofthecovidpandemic: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/os-signs-petition-to-open-ontario-skateparks-during-the-third-wave-of-the-covid-pandemic",
  path: "/post/os-signs-petition-to-open-ontario-skateparks-during-the-third-wave-of-the-covid-pandemic",
  title: "OS. signs petition to open Ontario Skateparks during the third wave of the Covid pandemic.",
  slug: "post--os-signs-petition-to-open-ontario-skateparks-during-the-third-wave-of-the-covid-pandemic",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostskatanicdisciplesatwarwithskatan2021: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/skatanic-disciples-at-war-with-skatan-2021",
  path: "/post/skatanic-disciples-at-war-with-skatan-2021",
  title: "Skatanic Disciples - At War with Skatan (2021)",
  slug: "post--skatanic-disciples-at-war-with-skatan-2021",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--skatanic-disciples-at-war-with-skatan-2021/01.png",
  ],
  videos: [
  ],
} as const;

export const blogPostskateboardingattheolympicstokyo2021: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/skateboarding-at-the-olympics-tokyo-2021",
  path: "/post/skateboarding-at-the-olympics-tokyo-2021",
  title: "Skateboarding at the Olympics - Tokyo 2021",
  slug: "post--skateboarding-at-the-olympics-tokyo-2021",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--skateboarding-at-the-olympics-tokyo-2021/01.png",
    "/imported/post--skateboarding-at-the-olympics-tokyo-2021/02.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostskatergirlshowcase2021shehercontests: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/skatergirlshowcase2021-she-her-contests",
  path: "/post/skatergirlshowcase2021-she-her-contests",
  title: "#skatergirlshowcase2021(She/Her) Contests",
  slug: "post--skatergirlshowcase2021-she-her-contests",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--skatergirlshowcase2021-she-her-contests/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostskatergirlshowcase2022iswhataugustisallabout: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/skatergirlshowcase2022-is-what-august-is-all-about",
  path: "/post/skatergirlshowcase2022-is-what-august-is-all-about",
  title: "#skatergirlshowcase2022 is what August is all about!",
  slug: "post--skatergirlshowcase2022-is-what-august-is-all-about",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--skatergirlshowcase2022-is-what-august-is-all-about/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostsoonerthanlaterjordanbandulaproducedbymiketemospushfast: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast",
  path: "/post/sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast",
  title: "\"Sooner than Later\" - Jordan Bandula produced by Mike Temos (Push Fast)",
  slug: "post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast/01.png",
    "/imported/post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast/02.jpg",
  ],
  videos: [
    "/imported/post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast/video-01.mp4",
  ],
} as const;

export const blogPostsponsormetroubl3: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/sponsorme_troubl3",
  path: "/post/sponsorme_troubl3",
  title: "#sponsorme_troubl3",
  slug: "post--sponsorme_troubl3",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--sponsorme_troubl3/01.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostsponsormetroubl3winnerseanspraggmeafordon: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/sponsorme_troubl3-winner-sean-spragg-meaford-on",
  path: "/post/sponsorme_troubl3-winner-sean-spragg-meaford-on",
  title: "#sponsorme_troubl3 WINNER!! - Sean Spragg (Meaford, ON)",
  slug: "post--sponsorme_troubl3-winner-sean-spragg-meaford-on",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--ontario-brand-feature-troubl3-skateboards/02.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPosttwentytwentytwomandate: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/twenty-twenty-two-mandate",
  path: "/post/twenty-twenty-two-mandate",
  title: "Twenty Twenty-Two Mandate",
  slug: "post--twenty-twenty-two-mandate",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
  ],
  videos: [
  ],
} as const;

export const blogPostwelcomekevinpagecompetitivechair: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/welcome-kevin-page-competitive-chair",
  path: "/post/welcome-kevin-page-competitive-chair",
  title: "Welcome Kevin Page - Competitive Chair",
  slug: "post--welcome-kevin-page-competitive-chair",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--change-is-coming/01.png",
  ],
  videos: [
  ],
} as const;

export const blogPostwinnersannounced: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/post/winners-announced",
  path: "/post/winners-announced",
  title: "Winners Announced!!",
  slug: "post--winners-announced",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/05.png",
    "/imported/post--4-20-2021/06.webp",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--winners-announced/01.jpg",
  ],
  videos: [
  ],
} as const;

export const shopProductpagecopyofimaproduct: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/product-page/copy-of-i-m-a-product",
  path: "/product-page/copy-of-i-m-a-product",
  title: "Flip Hoodie",
  slug: "product-page--copy-of-i-m-a-product",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--copy-of-i-m-a-product/01.webp",
    "/imported/product-page--zero-deck/02.jpg",
  ],
  videos: [
  ],
} as const;

export const shopProductpageshortystshirt: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/product-page/shorty-s-t-shirt",
  path: "/product-page/shorty-s-t-shirt",
  title: "OS Long Sleeve",
  slug: "product-page--shorty-s-t-shirt",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--shorty-s-t-shirt/01.jpg",
    "/imported/product-page--zero-deck/02.jpg",
  ],
  videos: [
  ],
} as const;

export const shopProductpageskatetoque: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/product-page/skate-toque",
  path: "/product-page/skate-toque",
  title: "Skate Toque",
  slug: "product-page--skate-toque",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--skate-toque/01.webp",
    "/imported/product-page--zero-deck/02.jpg",
  ],
  videos: [
  ],
} as const;

export const shopProductpagezerodeck: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/product-page/zero-deck",
  path: "/product-page/zero-deck",
  title: "ZERO Deck",
  slug: "product-page--zero-deck",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/product-page--zero-deck/01.webp",
    "/imported/product-page--zero-deck/02.jpg",
  ],
  videos: [
  ],
} as const;

export const shredcentral: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/shred-central",
  path: "/shred-central",
  title: "SHRED CENTRAL",
  slug: "shred-central",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/shred-central/01.jpg",
    "/imported/shred-central/02.jpg",
    "/imported/shred-central/03.jpg",
    "/imported/shred-central/04.jpg",
    "/imported/shred-central/05.jpg",
    "/imported/shred-central/06.jpg",
  ],
  videos: [
  ],
} as const;

export const skaters: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/skaters",
  path: "/skaters",
  title: "SPOTS",
  slug: "skaters",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/skaters/01.jpg",
  ],
  videos: [
  ],
} as const;

export const skaters1: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/skaters-1",
  path: "/skaters-1",
  title: "SKATERS",
  slug: "skaters-1",
  images: [
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/skaters-1/01.jpg",
    "/imported/skaters-1/02.jpg",
    "/imported/skaters-1/03.png",
    "/imported/skaters-1/04.png",
    "/imported/skaters-1/05.jpg",
    "/imported/skaters-1/06.jpg",
    "/imported/skaters-1/07.png",
    "/imported/skaters-1/08.jpg",
    "/imported/skaters-1/09.png",
    "/imported/skaters-1/10.jpg",
    "/imported/skaters-1/11.png",
    "/imported/skaters-1/12.jpg",
  ],
  videos: [
  ],
} as const;

export const theboard: PageMedia = {
  url: "https://www.ontarioskateboarding.ca/the-board",
  path: "/the-board",
  title: "ABOUT OS",
  slug: "the-board",
  images: [
    "/imported/ams/04.png",
    "/imported/ams/07.jpg",
    "/imported/event-details--dunbat-2018-1/01.jpg",
    "/imported/post--4-20-2021/01.png",
    "/imported/post--4-20-2021/02.png",
    "/imported/post--4-20-2021/03.png",
    "/imported/post--4-20-2021/04.jpg",
    "/imported/post--4-20-2021/07.jpg",
    "/imported/post--after_school_specialists_skateboarding101-2nd-annual-results/01.png",
    "/imported/post--change-is-coming/01.png",
    "/imported/post--kickflip_kickoff/01.jpg",
    "/imported/post--skatergirlshowcase2022-is-what-august-is-all-about/01.jpg",
    "/imported/the-board/01.png",
    "/imported/the-board/02.png",
    "/imported/the-board/03.png",
    "/imported/the-board/04.jpg",
    "/imported/the-board/05.jpg",
    "/imported/the-board/06.jpg",
    "/imported/the-board/07.png",
    "/imported/the-board/08.jpg",
    "/imported/the-board/09.jpg",
    "/imported/the-board/10.jpg",
    "/imported/the-board/11.jpg",
    "/imported/the-board/12.jpg",
    "/imported/the-board/13.jpg",
    "/imported/the-board/14.jpg",
    "/imported/the-board/15.jpeg",
    "/imported/the-board/16.png",
    "/imported/the-board/17.png",
    "/imported/the-board/18.jpeg",
    "/imported/the-board/19.png",
  ],
  videos: [
  ],
} as const;

export const blogPages = {
  _4202021: blogPost4202021,
  _5YearsRunningFy25: blogPost5yearsrunningfy25,
  _66ThievesPartnerWithOs: blogPost66thievespartnerwithos,
  _66ThievesTricksAndTipsFeatureBacksideFlip: blogPost66thievestricksandtipsfeaturebacksideflip,
  afterSchoolSpecialistsSkateboarding101: blogPostafterschoolspecialistsskateboarding101,
  afterSchoolSpecialistsSkateboarding1012ndAnnualResults: blogPostafterschoolspecialistsskateboarding1012ndannualresults,
  behindTheSceneAudioSeries: blogPostbehindthesceneaudioseries,
  blastOff: blogPostblastoff,
  canadianSkateboardChroniclesAndOsUnite: blogPostcanadianskateboardchroniclesandosunite,
  changeIsComing: blogPostchangeiscoming,
  comacanInterviewsOs: blogPostcomacaninterviewsos,
  finalPostOf2023: blogPostfinalpostof2023,
  goSkateboarding: blogPostgoskateboarding,
  goSkateboardingDay: blogPostgoskateboardingday,
  inauguralOsBoardMeetingFebruary222023: blogPostinauguralosboardmeetingfebruary222023,
  kickflipKickoff: blogPostkickflipkickoff,
  kickflipKickoffSecondAnnualOutdoorSeasonKickoffChallenge: blogPostkickflipkickoffsecondannualoutdoorseasonkickoffchallenge,
  monthlyFeaturesSkatersAndKeystoneSkateShops: blogPostmonthlyfeaturesskatersandkeystoneskateshops,
  odeToTheVanOffTheWall: blogPostodetothevanoffthewall,
  ontarioBrandFeatureTroubl3Skateboards: blogPostontariobrandfeaturetroubl3skateboards,
  ontarioSkateboardingReleasesNewTShirtDesign: blogPostontarioskateboardingreleasesnewtshirtdesign,
  osCelebratesEarthDaySoShouldYou: blogPostoscelebratesearthdaysoshouldyou,
  osSignsPetitionToOpenOntarioSkateparksDuringTheThirdWaveOfTheCovidPandemic: blogPostossignspetitiontoopenontarioskateparksduringthethirdwaveofthecovidpandemic,
  skatanicDisciplesAtWarWithSkatan2021: blogPostskatanicdisciplesatwarwithskatan2021,
  skateboardingAtTheOlympicsTokyo2021: blogPostskateboardingattheolympicstokyo2021,
  skatergirlshowcase2021SheHerContests: blogPostskatergirlshowcase2021shehercontests,
  skatergirlshowcase2022IsWhatAugustIsAllAbout: blogPostskatergirlshowcase2022iswhataugustisallabout,
  soonerThanLaterJordanBandulaProducedByMikeTemosPushFast: blogPostsoonerthanlaterjordanbandulaproducedbymiketemospushfast,
  sponsormeTroubl3: blogPostsponsormetroubl3,
  sponsormeTroubl3WinnerSeanSpraggMeafordOn: blogPostsponsormetroubl3winnerseanspraggmeafordon,
  twentyTwentyTwoMandate: blogPosttwentytwentytwomandate,
  welcomeKevinPageCompetitiveChair: blogPostwelcomekevinpagecompetitivechair,
  winnersAnnounced: blogPostwinnersannounced,
} as const;

export const eventsPages = {
  campbellfordJam: eventsEventdetailscampbellfordjam,
  charitySkateAThon: eventsEventdetailscharityskateathon,
  charitySkateAThon1: eventsEventdetailscharityskateathon1,
  dunbat20181: eventsEventdetailsdunbat20181,
  goSkateDay20241: eventsEventdetailsgoskateday20241,
  goSkateDay2025: eventsEventdetailsgoskateday2025,
  shredSeriesOntarioSkateloft: eventsEventdetailsshredseriesontarioskateloft,
  skateCreateWorkshop: eventsEventdetailsskatecreateworkshop,
  skateCreateWorkshop1: eventsEventdetailsskatecreateworkshop1,
} as const;

export const shopPages = {
  allProducts: shopCategoryallproducts,
  copyOfIMAProduct: shopProductpagecopyofimaproduct,
  shortySTShirt: shopProductpageshortystshirt,
  skateToque: shopProductpageskatetoque,
  zeroDeck: shopProductpagezerodeck,
} as const;

export const sitePages = {
  home: home,
  about3: about3,
  aboutUs: aboutus,
  ams: ams,
  archives: archives,
  blog: blog,
  canadaSkateboardsSlurpeeOpen2023: canadaskateboardsslurpeeopen2023,
  comingSoon03: comingsoon03,
  contact2: contact2,
  contactUs: contactus,
  dunbat2018: dunbat2018,
  dunbat2021: dunbat2021,
  dunbat2022: dunbat2022,
  eventList: eventlist,
  events: events,
  lilRippers: lilrippers,
  links: links,
  news: news,
  news1: news1,
  og: og,
  ogLegends1: oglegends1,
  originOfSkateboarding: originofskateboarding,
  shredCentral: shredcentral,
  skaters: skaters,
  skaters1: skaters1,
  theBoard: theboard,
} as const;

export const allPages: Record<string, PageMedia> = {
  "/": home,
  "/about-3": about3,
  "/about-us": aboutus,
  "/ams": ams,
  "/archives": archives,
  "/blog": blog,
  "/canada-skateboards-slurpee-open-2023": canadaskateboardsslurpeeopen2023,
  "/category/all-products": shopCategoryallproducts,
  "/coming-soon-03": comingsoon03,
  "/contact-2": contact2,
  "/contact-us": contactus,
  "/dunbat-2018": dunbat2018,
  "/dunbat-2021": dunbat2021,
  "/dunbat-2022": dunbat2022,
  "/event-details/campbellford-jam": eventsEventdetailscampbellfordjam,
  "/event-details/charity-skate-a-thon": eventsEventdetailscharityskateathon,
  "/event-details/charity-skate-a-thon-1": eventsEventdetailscharityskateathon1,
  "/event-details/dunbat-2018-1": eventsEventdetailsdunbat20181,
  "/event-details/go-skate-day-2024-1": eventsEventdetailsgoskateday20241,
  "/event-details/go-skate-day-2025": eventsEventdetailsgoskateday2025,
  "/event-details/shred-series-ontario-skateloft": eventsEventdetailsshredseriesontarioskateloft,
  "/event-details/skate-create-workshop": eventsEventdetailsskatecreateworkshop,
  "/event-details/skate-create-workshop-1": eventsEventdetailsskatecreateworkshop1,
  "/event-list": eventlist,
  "/events": events,
  "/lil-rippers": lilrippers,
  "/links": links,
  "/news": news,
  "/news-1": news1,
  "/og": og,
  "/og-legends-1": oglegends1,
  "/origin-of-skateboarding": originofskateboarding,
  "/post/4-20-2021": blogPost4202021,
  "/post/5-years-running-fy25": blogPost5yearsrunningfy25,
  "/post/66-thieves-partner-with-os": blogPost66thievespartnerwithos,
  "/post/66-thieves-tricks-and-tips-feature-backside-flip": blogPost66thievestricksandtipsfeaturebacksideflip,
  "/post/after_school_specialists_skateboarding101": blogPostafterschoolspecialistsskateboarding101,
  "/post/after_school_specialists_skateboarding101-2nd-annual-results": blogPostafterschoolspecialistsskateboarding1012ndannualresults,
  "/post/behind-the-scene-audio-series": blogPostbehindthesceneaudioseries,
  "/post/blast-off": blogPostblastoff,
  "/post/canadian-skateboard-chronicles-and-os-unite": blogPostcanadianskateboardchroniclesandosunite,
  "/post/change-is-coming": blogPostchangeiscoming,
  "/post/comacan-interviews-os": blogPostcomacaninterviewsos,
  "/post/final-post-of-2023": blogPostfinalpostof2023,
  "/post/go-skateboarding": blogPostgoskateboarding,
  "/post/go-skateboarding-day": blogPostgoskateboardingday,
  "/post/inaugural-os-board-meeting-february-22-2023": blogPostinauguralosboardmeetingfebruary222023,
  "/post/kickflip_kickoff": blogPostkickflipkickoff,
  "/post/kickflip_kickoff-second-annual-outdoor-season-kickoff-challenge": blogPostkickflipkickoffsecondannualoutdoorseasonkickoffchallenge,
  "/post/monthly-features-skaters-and-keystone-skate-shops": blogPostmonthlyfeaturesskatersandkeystoneskateshops,
  "/post/ode-to-the-van-off-the-wall": blogPostodetothevanoffthewall,
  "/post/ontario-brand-feature-troubl3-skateboards": blogPostontariobrandfeaturetroubl3skateboards,
  "/post/ontario-skateboarding-releases-new-t-shirt-design": blogPostontarioskateboardingreleasesnewtshirtdesign,
  "/post/os-celebrates-earth-day-so-should-you": blogPostoscelebratesearthdaysoshouldyou,
  "/post/os-signs-petition-to-open-ontario-skateparks-during-the-third-wave-of-the-covid-pandemic": blogPostossignspetitiontoopenontarioskateparksduringthethirdwaveofthecovidpandemic,
  "/post/skatanic-disciples-at-war-with-skatan-2021": blogPostskatanicdisciplesatwarwithskatan2021,
  "/post/skateboarding-at-the-olympics-tokyo-2021": blogPostskateboardingattheolympicstokyo2021,
  "/post/skatergirlshowcase2021-she-her-contests": blogPostskatergirlshowcase2021shehercontests,
  "/post/skatergirlshowcase2022-is-what-august-is-all-about": blogPostskatergirlshowcase2022iswhataugustisallabout,
  "/post/sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast": blogPostsoonerthanlaterjordanbandulaproducedbymiketemospushfast,
  "/post/sponsorme_troubl3": blogPostsponsormetroubl3,
  "/post/sponsorme_troubl3-winner-sean-spragg-meaford-on": blogPostsponsormetroubl3winnerseanspraggmeafordon,
  "/post/twenty-twenty-two-mandate": blogPosttwentytwentytwomandate,
  "/post/welcome-kevin-page-competitive-chair": blogPostwelcomekevinpagecompetitivechair,
  "/post/winners-announced": blogPostwinnersannounced,
  "/product-page/copy-of-i-m-a-product": shopProductpagecopyofimaproduct,
  "/product-page/shorty-s-t-shirt": shopProductpageshortystshirt,
  "/product-page/skate-toque": shopProductpageskatetoque,
  "/product-page/zero-deck": shopProductpagezerodeck,
  "/shred-central": shredcentral,
  "/skaters": skaters,
  "/skaters-1": skaters1,
  "/the-board": theboard,
} as const;

export const allImages: readonly string[] = [
  "/imported/about-3/01.jpg",
  "/imported/about-3/02.jpg",
  "/imported/about-us/01.png",
  "/imported/about-us/02.png",
  "/imported/about-us/03.png",
  "/imported/about-us/04.png",
  "/imported/ams/01.jpg",
  "/imported/ams/02.jpg",
  "/imported/ams/03.jpg",
  "/imported/ams/04.png",
  "/imported/ams/05.jpeg",
  "/imported/ams/06.jpg",
  "/imported/ams/07.jpg",
  "/imported/ams/08.jpg",
  "/imported/ams/09.png",
  "/imported/blog/01.png",
  "/imported/blog/02.png",
  "/imported/canada-skateboards-slurpee-open-2023/01.jpg",
  "/imported/canada-skateboards-slurpee-open-2023/02.jpg",
  "/imported/canada-skateboards-slurpee-open-2023/03.jpg",
  "/imported/canada-skateboards-slurpee-open-2023/04.jpg",
  "/imported/canada-skateboards-slurpee-open-2023/05.jpg",
  "/imported/canada-skateboards-slurpee-open-2023/06.jpg",
  "/imported/canada-skateboards-slurpee-open-2023/07.jpg",
  "/imported/canada-skateboards-slurpee-open-2023/08.jpg",
  "/imported/category--all-products/01.jpg",
  "/imported/contact-2/01.jpg",
  "/imported/dunbat-2018/01.png",
  "/imported/dunbat-2018/02.jpg",
  "/imported/dunbat-2018/03.jpg",
  "/imported/dunbat-2018/04.jpg",
  "/imported/dunbat-2018/05.jpg",
  "/imported/dunbat-2018/06.jpg",
  "/imported/dunbat-2018/07.jpg",
  "/imported/dunbat-2018/08.jpg",
  "/imported/dunbat-2018/09.jpg",
  "/imported/dunbat-2018/10.jpg",
  "/imported/dunbat-2018/11.jpg",
  "/imported/dunbat-2018/12.jpg",
  "/imported/dunbat-2018/13.jpg",
  "/imported/dunbat-2018/14.jpg",
  "/imported/dunbat-2018/15.jpg",
  "/imported/dunbat-2018/16.jpg",
  "/imported/dunbat-2018/17.jpg",
  "/imported/dunbat-2018/18.jpg",
  "/imported/dunbat-2021/01.jpg",
  "/imported/dunbat-2021/02.jpg",
  "/imported/dunbat-2021/03.jpg",
  "/imported/dunbat-2021/04.jpg",
  "/imported/dunbat-2021/05.jpg",
  "/imported/dunbat-2021/06.jpg",
  "/imported/dunbat-2021/07.jpg",
  "/imported/dunbat-2021/08.jpg",
  "/imported/dunbat-2022/01.jpg",
  "/imported/dunbat-2022/02.jpg",
  "/imported/dunbat-2022/03.png",
  "/imported/dunbat-2022/04.png",
  "/imported/dunbat-2022/05.jpg",
  "/imported/dunbat-2022/06.png",
  "/imported/dunbat-2022/07.jpg",
  "/imported/dunbat-2022/08.png",
  "/imported/dunbat-2022/09.png",
  "/imported/dunbat-2022/10.jpg",
  "/imported/dunbat-2022/11.jpg",
  "/imported/dunbat-2022/12.png",
  "/imported/dunbat-2022/13.png",
  "/imported/event-details--charity-skate-a-thon/01.jpg",
  "/imported/event-details--dunbat-2018-1/01.jpg",
  "/imported/event-details--go-skate-day-2025/01.jpg",
  "/imported/event-details--skate-create-workshop/01.png",
  "/imported/events/01.jpg",
  "/imported/home/01.png",
  "/imported/home/02.jpg",
  "/imported/home/03.jpg",
  "/imported/home/04.png",
  "/imported/lil-rippers/01.jpg",
  "/imported/lil-rippers/02.jpg",
  "/imported/lil-rippers/03.jpg",
  "/imported/lil-rippers/04.jpeg",
  "/imported/lil-rippers/05.png",
  "/imported/lil-rippers/06.png",
  "/imported/lil-rippers/07.jpg",
  "/imported/lil-rippers/08.png",
  "/imported/lil-rippers/09.jpg",
  "/imported/lil-rippers/10.jpg",
  "/imported/lil-rippers/11.jpg",
  "/imported/lil-rippers/12.jpg",
  "/imported/lil-rippers/13.jpg",
  "/imported/lil-rippers/14.png",
  "/imported/lil-rippers/15.gif",
  "/imported/links/01.jpg",
  "/imported/links/02.png",
  "/imported/links/03.jpg",
  "/imported/links/04.jpg",
  "/imported/links/05.png",
  "/imported/links/06.png",
  "/imported/links/07.jpg",
  "/imported/links/08.png",
  "/imported/links/09.jpg",
  "/imported/links/10.jpg",
  "/imported/links/11.png",
  "/imported/links/12.png",
  "/imported/links/13.png",
  "/imported/links/14.png",
  "/imported/links/15.jpg",
  "/imported/links/16.png",
  "/imported/links/17.png",
  "/imported/links/18.png",
  "/imported/news/01.jpg",
  "/imported/news/02.png",
  "/imported/news/03.jpg",
  "/imported/og/01.png",
  "/imported/origin-of-skateboarding/01.jpg",
  "/imported/origin-of-skateboarding/02.jpg",
  "/imported/origin-of-skateboarding/03.jpg",
  "/imported/origin-of-skateboarding/04.jpg",
  "/imported/origin-of-skateboarding/05.jpg",
  "/imported/origin-of-skateboarding/06.jpg",
  "/imported/origin-of-skateboarding/07.jpg",
  "/imported/post--4-20-2021/01.png",
  "/imported/post--4-20-2021/02.png",
  "/imported/post--4-20-2021/03.png",
  "/imported/post--4-20-2021/04.jpg",
  "/imported/post--4-20-2021/05.png",
  "/imported/post--4-20-2021/06.webp",
  "/imported/post--4-20-2021/07.jpg",
  "/imported/post--66-thieves-partner-with-os/01.jpg",
  "/imported/post--after_school_specialists_skateboarding101-2nd-annual-results/01.png",
  "/imported/post--after_school_specialists_skateboarding101/01.jpg",
  "/imported/post--canadian-skateboard-chronicles-and-os-unite/01.jpg",
  "/imported/post--change-is-coming/01.png",
  "/imported/post--change-is-coming/02.jpg",
  "/imported/post--comacan-interviews-os/01.jpeg",
  "/imported/post--final-post-of-2023/01.png",
  "/imported/post--final-post-of-2023/02.png",
  "/imported/post--final-post-of-2023/03.png",
  "/imported/post--go-skateboarding/01.png",
  "/imported/post--inaugural-os-board-meeting-february-22-2023/01.jpg",
  "/imported/post--kickflip_kickoff-second-annual-outdoor-season-kickoff-challenge/01.jpg",
  "/imported/post--kickflip_kickoff/01.jpg",
  "/imported/post--ode-to-the-van-off-the-wall/01.jpg",
  "/imported/post--ontario-brand-feature-troubl3-skateboards/01.jpg",
  "/imported/post--ontario-brand-feature-troubl3-skateboards/02.jpg",
  "/imported/post--ontario-skateboarding-releases-new-t-shirt-design/01.png",
  "/imported/post--os-celebrates-earth-day-so-should-you/01.jpg",
  "/imported/post--skatanic-disciples-at-war-with-skatan-2021/01.png",
  "/imported/post--skateboarding-at-the-olympics-tokyo-2021/01.png",
  "/imported/post--skateboarding-at-the-olympics-tokyo-2021/02.jpg",
  "/imported/post--skatergirlshowcase2021-she-her-contests/01.jpg",
  "/imported/post--skatergirlshowcase2022-is-what-august-is-all-about/01.jpg",
  "/imported/post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast/01.png",
  "/imported/post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast/02.jpg",
  "/imported/post--sponsorme_troubl3/01.jpg",
  "/imported/post--winners-announced/01.jpg",
  "/imported/product-page--copy-of-i-m-a-product/01.webp",
  "/imported/product-page--shorty-s-t-shirt/01.jpg",
  "/imported/product-page--skate-toque/01.webp",
  "/imported/product-page--zero-deck/01.webp",
  "/imported/product-page--zero-deck/02.jpg",
  "/imported/shred-central/01.jpg",
  "/imported/shred-central/02.jpg",
  "/imported/shred-central/03.jpg",
  "/imported/shred-central/04.jpg",
  "/imported/shred-central/05.jpg",
  "/imported/shred-central/06.jpg",
  "/imported/skaters-1/01.jpg",
  "/imported/skaters-1/02.jpg",
  "/imported/skaters-1/03.png",
  "/imported/skaters-1/04.png",
  "/imported/skaters-1/05.jpg",
  "/imported/skaters-1/06.jpg",
  "/imported/skaters-1/07.png",
  "/imported/skaters-1/08.jpg",
  "/imported/skaters-1/09.png",
  "/imported/skaters-1/10.jpg",
  "/imported/skaters-1/11.png",
  "/imported/skaters-1/12.jpg",
  "/imported/skaters/01.jpg",
  "/imported/the-board/01.png",
  "/imported/the-board/02.png",
  "/imported/the-board/03.png",
  "/imported/the-board/04.jpg",
  "/imported/the-board/05.jpg",
  "/imported/the-board/06.jpg",
  "/imported/the-board/07.png",
  "/imported/the-board/08.jpg",
  "/imported/the-board/09.jpg",
  "/imported/the-board/10.jpg",
  "/imported/the-board/11.jpg",
  "/imported/the-board/12.jpg",
  "/imported/the-board/13.jpg",
  "/imported/the-board/14.jpg",
  "/imported/the-board/15.jpeg",
  "/imported/the-board/16.png",
  "/imported/the-board/17.png",
  "/imported/the-board/18.jpeg",
  "/imported/the-board/19.png",
] as const;

export const allVideos: readonly string[] = [
  "/imported/post--sooner-than-later-jordan-bandula-produced-by-mike-temos-push-fast/video-01.mp4",
] as const;
